# ===============================
# MySQL Deployment (with hostPath storage)
# ===============================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
        tier: backend
    spec:
      containers:
        - name: mysql
          image: minj1993/java-project-backend:v1.0.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "Login%12345"
            - name: MYSQL_DATABASE
              value: "db1"
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql

                

      volumes:
        - name: mysql-storage
          hostPath:
            path: /home/ubuntu/mysql-data
            type: DirectoryOrCreate
        - name: mysql-init
          hostPath:
            path: /home/ubuntu/mysql-backend/init.sql
            type: FileOrCreate

# ===============================
# MySQL Service
# ===============================
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service1
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP

# ===============================
# Frontend Deployment
# ===============================
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: java-frontend
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-frontend
  template:
    metadata:
      labels:
        app: java-frontend
        tier: frontend
    spec:
      containers:
        - name: frontend
          image: minj1993/java-project-jsp-frontend:v1.0.1
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: "mysql-service1"
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: "db1"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: "Login%12345"

# ===============================
# Frontend NodePort Service
# ===============================
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-nodeport
spec:
  selector:
    app: java-frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort

