# Dockerfile-frontend
FROM tomcat:10.1-jdk17
COPY java-test.war /usr/local/tomcat/webapps/
COPY mysql-connector-j-9.1.0.jar /usr/local/tomcat/lib/
COPY wait-for-it.sh /wait-for-it.sh
RUN chmod +x /wait-for-it.sh

EXPOSE 8080

CMD ["/wait-for-it.sh", "mysql:3306", "--", "catalina.sh", "run"]



